# Generated by Django 5.1.15 on 2026-03-29 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_customer_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineorder',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_orders', to='game.player'),
        ),
    ]
