# Generated by Django 6.0.3 on 2026-04-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_pipelineorder_receiver'),
        ('game', 'migration_phase_fields'),
    ]

    operations = [
    ]
