# Generated by Django 6.0.3 on 2026-04-07 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_merge_20260401_1621'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelineorder',
            name='receiver',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playersession',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playersession',
            name='last_week_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playersession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
