# Generated by Django 6.0.4 on 2026-04-15 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_pipelineorder_receiver_gamesession_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(blank=True, default='', max_length=20)),
                ('body', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_messages', to='game.gamesession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
